// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.quetzales5932.jack.autonomous;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.quetzales5932.jack.commands.DoNothing;
import org.quetzales5932.jack.commands.DriveBackwards;
import org.quetzales5932.jack.commands.DriveForwards;
import org.quetzales5932.jack.commands.OpenGear;
import org.quetzales5932.jack.subsystems.*;

/**
 *
 */
public class Center extends CommandGroup {
	private final double waitTime = 1;


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public Center() {
        addSequential(new DriveForwards(4));
 
    } 
}
