// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.quetzales5932.jack.subsystems;

import org.quetzales5932.jack.RobotMap;
import org.quetzales5932.jack.commands.*;

import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class BallContainer extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Servo ballServo1 = RobotMap.ballContainerBallServo1;
    private final int ballServoOpenAngle = 90;
    private final int ballServoClosedAngle = 135;
    private String state;
    
    private final SpeedController spinner = RobotMap.ballContainerSpinner;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public double speed = RobotMap.highSpeed;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void throwBalls(){
    	spinner.set(speed);
    }
    
    public void stopSpinner(){
    	spinner.set(0);
    }
    
    public void open(){
    	ballServo1.setAngle(ballServoOpenAngle);
    	System.out.println("Pelotas abierto");
    	state = "abierto";
    }
    
    public void close(){
    	ballServo1.setAngle(ballServoClosedAngle);
    	System.out.println("Pelotas cerrado");
    	state = "cerrado";
    }
    
    public String getState(){
    	return state;
    }
}




